### ISSUE TITLE
terraform init issue

### ISSUE THREAD

**Issue by julianhall** [jbrt/ec2cryptomatic-serverless#1]
Hi Julien, 
I would like to give this a shot but am running into the following issues.

I've cloned the repo and installed terraform.exe and get the following when running
terraform.exe init

```
PS D:\_dev\ec2cryptomatic-serverless\terraform> terraform.exe init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "aws" v1.60.0 is not compatible with Terraform 0.12.20.

Provider version 2.7.0 is the earliest compatible version. Select it with
the following version constraint:

        version = "~> 2.7"

Terraform checked all of the plugin versions matching the given constraint:
    1.60.0

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.


Error: incompatible provider version
```

I'm probably missing something basic, but any help would be appreciated.

**Comment by jbrt** [comment]
Hello @julianhall !

This version was initially built for a version 0.11.x of Terraform.
Version 0.12.x was a big one with many potential breaking changes.

But this code still works if you downgrade your Terraform version to 0.11.14, I've tested few minutes ago (don't forget to delete the .terraform folder before running 0.11.14 version).

If I'll found some spare time in the next weeks, I'll try to upgrade this template to 0.12.

Regards

**Comment by julianhall** [comment]
Thanks for getting back! I'll downgrade and give it ago - appreciate the quick response. 
This will be quite a time saver for me.

**Comment by julianhall** [comment]
That worked like a charm thanks.

**Comment by jbrt** [comment]
Hello @julianhall 

Just for your information, I've released a new version of the project.
This new version handle Terraform 0.12.x version.

Regards,

**Comment by julianhall** [comment]
Thanks!
